### ISSUE TITLE
Wrong link to "Core REST Implementation"

### ISSUE THREAD

**Issue by patric0303** [NetAppDocs/astra-automation#23]
Page: [Before you begin](https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html)

Link to "Core REST Implementation" https://docs.netapp.com/us-en/astra-automation/rest-core/rest_implementation.html results in 404 error.

**Comment by dmp-netapp** [comment]
I see the broken link. Expect to fix today.

**Comment by dmp-netapp** [comment]
The updated content is now live. Closing.
