### ISSUE TITLE
Error in first sentence

### ISSUE THREAD

**Issue by patric0303** [NetAppDocs/astra-automation#24]
Page: [List users](https://docs.netapp.com/us-en/astra-automation/workflows_infra/wf_list_users.html)

First sentence should probably read: "You can list the users that are defined for a specific Astra account.", not "...applications..."

**Comment by dmp-netapp** [comment]
I see the error. Expect to fix today.

**Comment by dmp-netapp** [comment]
The updated content is now live. Closing.
