### ISSUE TITLE
No Swagger documentation for ACC

### ISSUE THREAD

**Issue by netapp-dgrund** [NetAppDocs/astra-automation#67]
Page: [Get an API token](https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html)

Please add documentation on get the token for ACC and how to work with Swagger on ACC

**Comment by dmp-netapp** [comment]
Thanks for the feedback. Reviewing now.

**Comment by dmp-netapp** [comment]
I've confirmed that the two following procedures as currently documented apply to both the ACS (cloud) and ACC (on-prem) deployments:

* Get an API token:  https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html
* Access the online Swagger doc: https://docs.netapp.com/us-en/astra-automation/get-started/online_api_ref.html

I will update these pages to clearly state they apply to both.

**Comment by dmp-netapp** [comment]
I will update the second topic with additional content around executing an API call from the Swagger page and the authentication steps needed.

**Comment by dmp-netapp** [comment]
The update is live. Closing this issue.
